---
site_name: Blaze Documentation
site_url: https://Trailblaze-Software.github.io/Blaze/
repo_url: https://github.com/Trailblaze-Software/Blaze
repo_name: Trailblaze-Software/Blaze
docs_dir: src
site_dir: ../site
theme:
  name: material
  logo: assets/images/blaze_icon.png
  favicon: assets/images/blaze_icon.png
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - assets/stylesheets/custom.css
extra:
  version:
    provider: mike
plugins:
  - search
  - mkdoxy:
      projects:
        blaze:
          src-dirs: ../src
          full-doc: True
          doxy-cfg:
            file: Doxyfile
validation:
  omitted_files: ignore
  not_found: ignore
nav:
  - Home: index.md
  - Installation:
      - installation/index.md
      - Building from Source: installation/build-from-source.md
  - Usage:
      - usage/index.md
      - QGIS Plugin: usage/qgis-plugin.md
  - Developers Reference:
      - reference/index.md
      - Classes: blaze/annotated.md
      - Functions: blaze/functions.md
      - Files: blaze/files.md
      - Releasing: reference/releasing.md
  - About:
      - about/index.md
      - License: about/license.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
